version: '3.7'

services:
  app:
    image: hundredacrewood
    build: ./app
    container_name: hundredacrewood
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always

  db:
    image: db
    build: ./db
    container_name: mysql
    restart: always
    env_file: ./db/.env